# yaml-language-server: $schema=https://raw.githubusercontent.com/runkids/skillshare/main/schemas/project-config.schema.json
targets:
  - universal
  - claude
skills:
  - name: frontend-design
    source: github.com/anthropics/skills/skills/frontend-design
  - name: canvas-design
    source: github.com/anthropics/skills/skills/canvas-design
  - name: pandoc
    source: github.com/majiayu000/claude-skill-registry/skills/documents/pandoc
  - name: rtk
    source: /home/zakharov/.config/skillshare/skills/rtk
audit:
  block_threshold: CRITICAL
